### PR TITLE
Add `REDISMODULE_NOTIFY_LOADED` to NotifyEvent clags

### PR DESCRIPTION
**Pull request by rcelha**
I came across a use case where I create a timer after writing to my data type. To create the timer after it loads from the rdb, I need to hook it up with the REDISMODULE_NOTIFY_LOADED event.

I don' t know if there is a reason for not supporting it, if there is just let me know

### CODE REVIEW

**Comment by slavak** [comment]
Can't think of any good reason not to have it. Have you by chance tested this with your module yet?

**Comment by rcelha** [comment]
Hey @slavak, I did test with my module.

The lines are commeted because I didn't want to point it to my fork, but you can see it [here](https://github.com/rcelha/redelay/pull/3/files#diff-b1a35a68f14e696205874893c07fd24fdb88882b47c23cc0e0c80a30c7d53759R106) and [here](https://github.com/rcelha/redelay/pull/3/files#diff-b1a35a68f14e696205874893c07fd24fdb88882b47c23cc0e0c80a30c7d53759R143)

**Comment by slavak** [comment]
That's great. Thank you!

**Comment by rcelha** [comment]
No worries :)

**Review by slavak — APPROVED** [review]

**Comment by slavak** [comment]
Ignore me. Just trying to jiggle the CircleCI check.

**Comment by slavak** [comment]
Thanks for the contribution @rcelha!

**Comment by rcelha** [comment]
Thanks for merging it @slavak :bow:

**Pull request merged**
