### PR TITLE
Add integration test infrastructure for example modules

### PR DESCRIPTION
**Pull request by gavrie**
As discussed in #135, this PR adds infrastructure for integrations tests that can run the example modules inside Redis and perform tests against them.

The infra takes care of starting `redis-server` and shutting it down.

### CODE REVIEW

**Comment by gavrie** [comment]
@naphta does this provide what you need? If not, please let me know what's missing.

**Comment by naphta** [comment]
That looks pretty good to me. Not sure if the log is necessary to demonstrate it but all seems fairly clear to setup and use.

**Comment by gavrie** [comment]
> That looks pretty good to me. Not sure if the log is necessary to demonstrate it but all seems fairly clear to setup and use.

Thanks for the feedback. The log was committed by mistake; I've removed it.

**Comment by matobet** [comment]
Hi, I just wanted to post it here: as a part of my Redis module https://github.com/matobet/dragon-map/blob/master/tests/integration_test.rs I've developed a small "framework" for creating integration tests using procedural macros. (Your tests get "injected" the redis connection and other nice things). Might serve as a source of inspiration.

**Comment by gavrie** [comment]
> Hi, I just wanted to post it here: as a part of my Redis module https://github.com/matobet/dragon-map/blob/master/tests/integration_test.rs I've developed a small "framework" for creating integration tests using procedural macros. (Your tests get "injected" the redis connection and other nice things). Might serve as a source of inspiration.

@matobet that looks pretty cool 😄

**Comment by matobet** [comment]
> > Hi, I just wanted to post it here: as a part of my Redis module https://github.com/matobet/dragon-map/blob/master/tests/integration_test.rs I've developed a small "framework" for creating integration tests using procedural macros. (Your tests get "injected" the redis connection and other nice things). Might serve as a source of inspiration.
> 
> @matobet that looks pretty cool 😄

Feel free to carve out any parts you like 😊

**Review by gkorland — APPROVED** [review]

**Pull request merged**
